# configuration.yaml
application_port: 8000
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  # not too big of a deal to have this here right now.
  password: "password"
  database_name: "newsletter"